services:
 nextjs:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "3000:3000"
   volumes:
     - .:/app
   stdin_open: true
   tty: true

# volumes:
#   test-ts-site-volume:
#     name: test-ts-site
#     driver_opts:
#       o: bind
#       device: .
#       type: none
